### ISSUE TITLE
Tests require run_time.ini file in test directory

### ISSUE THREAD

**Issue by ericmtsai** [ElectionDataAnalysis/electiondata#309] opened 2020-10-26 17:30 UTC
As far as I can tell, the tests don't use the run_time.ini file in the current (calling) directory, but rather it needs to be in the test directory. I don't think this is a good way to do it. We should have it reference the current directory, which is what the rest of the code does, or be able to pass the location as a param.

**Comment by sfsinger19103** [comment] 2021-07-26 16:55
Duplicate of #138

**Closed by sfsinger19103** 2021-07-26 16:55 UTC
Labels: enhancement
